# Generated by Django 3.2.25 on 2025-02-18 23:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2083)),
                ('domain_name', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('stylesheets', models.IntegerField(default=0)),
                ('is_fully_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedUrlImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('scraped_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='url_scraper.scrapedurl')),
            ],
        ),
        migrations.AddIndex(
            model_name='scrapedurl',
            index=models.Index(fields=['created_at'], name='url_scraper_created_b52a33_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedurlimage',
            index=models.Index(fields=['scraped_url'], name='url_scraper_scraped_84243a_idx'),
        ),
        migrations.AlterModelOptions(
            name='scrapedurl',
            options={'ordering': ['-created_at']},
        ),
    ]
